Reference: "/path/to/Reference.fa"
Data: "/path/to/bam_files_folder"
Output: "/path/to/output_folder"
Sample: "/path/to/samples.tsv"
Annovar: "/path/to/Annovar_folder"
targt_bed: "/path/to/targets.bed"
